//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IDataLayer")]
public interface IDataLayer
{

    // CODEGEN: Параметр "GetTableResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/GetTable", ReplyAction = "http://tempuri.org/IDataLayer/GetTableResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetTableResponse GetTable(GetTableRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/GetTable", ReplyAction = "http://tempuri.org/IDataLayer/GetTableResponse")]
    System.Threading.Tasks.Task<GetTableResponse> GetTableAsync(GetTableRequest request);

    // CODEGEN: Параметр "GetTablesResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayAttribute".
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/GetTables", ReplyAction = "http://tempuri.org/IDataLayer/GetTablesResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetTablesResponse GetTables(GetTablesRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/GetTables", ReplyAction = "http://tempuri.org/IDataLayer/GetTablesResponse")]
    System.Threading.Tasks.Task<GetTablesResponse> GetTablesAsync(GetTablesRequest request);

    // CODEGEN: Параметр "connectionString" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/InsertData", ReplyAction = "http://tempuri.org/IDataLayer/InsertDataResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    InsertDataResponse InsertData(InsertDataRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/InsertData", ReplyAction = "http://tempuri.org/IDataLayer/InsertDataResponse")]
    System.Threading.Tasks.Task<InsertDataResponse> InsertDataAsync(InsertDataRequest request);

    // CODEGEN: Параметр "connectionString" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/DeleteDataById", ReplyAction = "http://tempuri.org/IDataLayer/DeleteDataByIdResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    DeleteDataByIdResponse DeleteDataById(DeleteDataByIdRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/DeleteDataById", ReplyAction = "http://tempuri.org/IDataLayer/DeleteDataByIdResponse")]
    System.Threading.Tasks.Task<DeleteDataByIdResponse> DeleteDataByIdAsync(DeleteDataByIdRequest request);

    // CODEGEN: Параметр "FindDataByValueResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/FindDataByValue", ReplyAction = "http://tempuri.org/IDataLayer/FindDataByValueResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    FindDataByValueResponse FindDataByValue(FindDataByValueRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/FindDataByValue", ReplyAction = "http://tempuri.org/IDataLayer/FindDataByValueResponse")]
    System.Threading.Tasks.Task<FindDataByValueResponse> FindDataByValueAsync(FindDataByValueRequest request);

    // CODEGEN: Параметр "FindDataByIdResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/FindDataById", ReplyAction = "http://tempuri.org/IDataLayer/FindDataByIdResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    FindDataByIdResponse FindDataById(FindDataByIdRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/FindDataById", ReplyAction = "http://tempuri.org/IDataLayer/FindDataByIdResponse")]
    System.Threading.Tasks.Task<FindDataByIdResponse> FindDataByIdAsync(FindDataByIdRequest request);

    // CODEGEN: Параметр "connectionString" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/EditDataById", ReplyAction = "http://tempuri.org/IDataLayer/EditDataByIdResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    EditDataByIdResponse EditDataById(EditDataByIdRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/EditDataById", ReplyAction = "http://tempuri.org/IDataLayer/EditDataByIdResponse")]
    System.Threading.Tasks.Task<EditDataByIdResponse> EditDataByIdAsync(EditDataByIdRequest request);

    // CODEGEN: Параметр "FindDataResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/FindData", ReplyAction = "http://tempuri.org/IDataLayer/FindDataResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    FindDataResponse FindData(FindDataRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/FindData", ReplyAction = "http://tempuri.org/IDataLayer/FindDataResponse")]
    System.Threading.Tasks.Task<FindDataResponse> FindDataAsync(FindDataRequest request);

    // CODEGEN: Параметр "ProductNameWithQuantityBiggerThan50HorizontalResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/ProductNameWithQuantityBiggerThan50Horizontal", ReplyAction = "http://tempuri.org/IDataLayer/ProductNameWithQuantityBiggerThan50HorizontalRespon" +
        "se")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ProductNameWithQuantityBiggerThan50HorizontalResponse ProductNameWithQuantityBiggerThan50Horizontal(ProductNameWithQuantityBiggerThan50HorizontalRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/ProductNameWithQuantityBiggerThan50Horizontal", ReplyAction = "http://tempuri.org/IDataLayer/ProductNameWithQuantityBiggerThan50HorizontalRespon" +
        "se")]
    System.Threading.Tasks.Task<ProductNameWithQuantityBiggerThan50HorizontalResponse> ProductNameWithQuantityBiggerThan50HorizontalAsync(ProductNameWithQuantityBiggerThan50HorizontalRequest request);

    // CODEGEN: Параметр "OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/OrderIdWhereEmployeeNameStartWithDandSumBetween500a" +
        "nd1000Vertical", ReplyAction = "http://tempuri.org/IDataLayer/OrderIdWhereEmployeeNameStartWithDandSumBetween500a" +
        "nd1000VerticalResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalResponse OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000Vertical(OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDataLayer/OrderIdWhereEmployeeNameStartWithDandSumBetween500a" +
        "nd1000Vertical", ReplyAction = "http://tempuri.org/IDataLayer/OrderIdWhereEmployeeNameStartWithDandSumBetween500a" +
        "nd1000VerticalResponse")]
    System.Threading.Tasks.Task<OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalResponse> OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalAsync(OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetTable", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class GetTableRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ConStr;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Table;

    public GetTableRequest()
    {
    }

    public GetTableRequest(string ConStr, string Table)
    {
        this.ConStr = ConStr;
        this.Table = Table;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetTableResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class GetTableResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public System.Data.DataTable GetTableResult;

    public GetTableResponse()
    {
    }

    public GetTableResponse(System.Data.DataTable GetTableResult)
    {
        this.GetTableResult = GetTableResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetTables", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class GetTablesRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string ConStr;

    public GetTablesRequest()
    {
    }

    public GetTablesRequest(string ConStr)
    {
        this.ConStr = ConStr;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetTablesResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class GetTablesResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public string[] GetTablesResult;

    public GetTablesResponse()
    {
    }

    public GetTablesResponse(string[] GetTablesResult)
    {
        this.GetTablesResult = GetTablesResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "InsertData", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class InsertDataRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string connectionString;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string tableName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string parameters;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string data;

    public InsertDataRequest()
    {
    }

    public InsertDataRequest(string connectionString, string tableName, string parameters, string data)
    {
        this.connectionString = connectionString;
        this.tableName = tableName;
        this.parameters = parameters;
        this.data = data;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "InsertDataResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class InsertDataResponse
{

    public InsertDataResponse()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "DeleteDataById", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class DeleteDataByIdRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string connectionString;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string tableName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string idColumnName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
    public int id;

    public DeleteDataByIdRequest()
    {
    }

    public DeleteDataByIdRequest(string connectionString, string tableName, string idColumnName, int id)
    {
        this.connectionString = connectionString;
        this.tableName = tableName;
        this.idColumnName = idColumnName;
        this.id = id;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "DeleteDataByIdResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class DeleteDataByIdResponse
{

    public DeleteDataByIdResponse()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "FindDataByValue", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class FindDataByValueRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string connectionString;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string tableName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string columnName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string columnValue;

    public FindDataByValueRequest()
    {
    }

    public FindDataByValueRequest(string connectionString, string tableName, string columnName, string columnValue)
    {
        this.connectionString = connectionString;
        this.tableName = tableName;
        this.columnName = columnName;
        this.columnValue = columnValue;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "FindDataByValueResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class FindDataByValueResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public System.Data.DataTable FindDataByValueResult;

    public FindDataByValueResponse()
    {
    }

    public FindDataByValueResponse(System.Data.DataTable FindDataByValueResult)
    {
        this.FindDataByValueResult = FindDataByValueResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "FindDataById", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class FindDataByIdRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string connectionString;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string tableName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string idColumnName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
    public int idValue;

    public FindDataByIdRequest()
    {
    }

    public FindDataByIdRequest(string connectionString, string tableName, string idColumnName, int idValue)
    {
        this.connectionString = connectionString;
        this.tableName = tableName;
        this.idColumnName = idColumnName;
        this.idValue = idValue;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "FindDataByIdResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class FindDataByIdResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public System.Data.DataTable FindDataByIdResult;

    public FindDataByIdResponse()
    {
    }

    public FindDataByIdResponse(System.Data.DataTable FindDataByIdResult)
    {
        this.FindDataByIdResult = FindDataByIdResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "EditDataById", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class EditDataByIdRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string connectionString;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string tableName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string idColumnName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
    public int idValue;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 4)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string parameters;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 5)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string data;

    public EditDataByIdRequest()
    {
    }

    public EditDataByIdRequest(string connectionString, string tableName, string idColumnName, int idValue, string parameters, string data)
    {
        this.connectionString = connectionString;
        this.tableName = tableName;
        this.idColumnName = idColumnName;
        this.idValue = idValue;
        this.parameters = parameters;
        this.data = data;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "EditDataByIdResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class EditDataByIdResponse
{

    public EditDataByIdResponse()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "FindData", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class FindDataRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string connectionString;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string tableName;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string filterExpression;

    public FindDataRequest()
    {
    }

    public FindDataRequest(string connectionString, string tableName, string filterExpression)
    {
        this.connectionString = connectionString;
        this.tableName = tableName;
        this.filterExpression = filterExpression;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "FindDataResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class FindDataResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public System.Data.DataTable FindDataResult;

    public FindDataResponse()
    {
    }

    public FindDataResponse(System.Data.DataTable FindDataResult)
    {
        this.FindDataResult = FindDataResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ProductNameWithQuantityBiggerThan50Horizontal", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ProductNameWithQuantityBiggerThan50HorizontalRequest
{

    public ProductNameWithQuantityBiggerThan50HorizontalRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ProductNameWithQuantityBiggerThan50HorizontalResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ProductNameWithQuantityBiggerThan50HorizontalResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public System.Data.DataTable ProductNameWithQuantityBiggerThan50HorizontalResult;

    public ProductNameWithQuantityBiggerThan50HorizontalResponse()
    {
    }

    public ProductNameWithQuantityBiggerThan50HorizontalResponse(System.Data.DataTable ProductNameWithQuantityBiggerThan50HorizontalResult)
    {
        this.ProductNameWithQuantityBiggerThan50HorizontalResult = ProductNameWithQuantityBiggerThan50HorizontalResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000Vertical", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalRequest
{

    public OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public System.Data.DataTable OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalResult;

    public OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalResponse()
    {
    }

    public OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalResponse(System.Data.DataTable OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalResult)
    {
        this.OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalResult = OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDataLayerChannel : IDataLayer, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DataLayerClient : System.ServiceModel.ClientBase<IDataLayer>, IDataLayer
{

    public DataLayerClient()
    {
    }

    public DataLayerClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public DataLayerClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public DataLayerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public DataLayerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetTableResponse IDataLayer.GetTable(GetTableRequest request)
    {
        return base.Channel.GetTable(request);
    }

    public System.Data.DataTable GetTable(string ConStr, string Table)
    {
        GetTableRequest inValue = new GetTableRequest();
        inValue.ConStr = ConStr;
        inValue.Table = Table;
        GetTableResponse retVal = ((IDataLayer)(this)).GetTable(inValue);
        return retVal.GetTableResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetTableResponse> IDataLayer.GetTableAsync(GetTableRequest request)
    {
        return base.Channel.GetTableAsync(request);
    }

    public System.Threading.Tasks.Task<GetTableResponse> GetTableAsync(string ConStr, string Table)
    {
        GetTableRequest inValue = new GetTableRequest();
        inValue.ConStr = ConStr;
        inValue.Table = Table;
        return ((IDataLayer)(this)).GetTableAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetTablesResponse IDataLayer.GetTables(GetTablesRequest request)
    {
        return base.Channel.GetTables(request);
    }

    public string[] GetTables(string ConStr)
    {
        GetTablesRequest inValue = new GetTablesRequest();
        inValue.ConStr = ConStr;
        GetTablesResponse retVal = ((IDataLayer)(this)).GetTables(inValue);
        return retVal.GetTablesResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetTablesResponse> IDataLayer.GetTablesAsync(GetTablesRequest request)
    {
        return base.Channel.GetTablesAsync(request);
    }

    public System.Threading.Tasks.Task<GetTablesResponse> GetTablesAsync(string ConStr)
    {
        GetTablesRequest inValue = new GetTablesRequest();
        inValue.ConStr = ConStr;
        return ((IDataLayer)(this)).GetTablesAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    InsertDataResponse IDataLayer.InsertData(InsertDataRequest request)
    {
        return base.Channel.InsertData(request);
    }

    public void InsertData(string connectionString, string tableName, string parameters, string data)
    {
        InsertDataRequest inValue = new InsertDataRequest();
        inValue.connectionString = connectionString;
        inValue.tableName = tableName;
        inValue.parameters = parameters;
        inValue.data = data;
        InsertDataResponse retVal = ((IDataLayer)(this)).InsertData(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<InsertDataResponse> IDataLayer.InsertDataAsync(InsertDataRequest request)
    {
        return base.Channel.InsertDataAsync(request);
    }

    public System.Threading.Tasks.Task<InsertDataResponse> InsertDataAsync(string connectionString, string tableName, string parameters, string data)
    {
        InsertDataRequest inValue = new InsertDataRequest();
        inValue.connectionString = connectionString;
        inValue.tableName = tableName;
        inValue.parameters = parameters;
        inValue.data = data;
        return ((IDataLayer)(this)).InsertDataAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    DeleteDataByIdResponse IDataLayer.DeleteDataById(DeleteDataByIdRequest request)
    {
        return base.Channel.DeleteDataById(request);
    }

    public void DeleteDataById(string connectionString, string tableName, string idColumnName, int id)
    {
        DeleteDataByIdRequest inValue = new DeleteDataByIdRequest();
        inValue.connectionString = connectionString;
        inValue.tableName = tableName;
        inValue.idColumnName = idColumnName;
        inValue.id = id;
        DeleteDataByIdResponse retVal = ((IDataLayer)(this)).DeleteDataById(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<DeleteDataByIdResponse> IDataLayer.DeleteDataByIdAsync(DeleteDataByIdRequest request)
    {
        return base.Channel.DeleteDataByIdAsync(request);
    }

    public System.Threading.Tasks.Task<DeleteDataByIdResponse> DeleteDataByIdAsync(string connectionString, string tableName, string idColumnName, int id)
    {
        DeleteDataByIdRequest inValue = new DeleteDataByIdRequest();
        inValue.connectionString = connectionString;
        inValue.tableName = tableName;
        inValue.idColumnName = idColumnName;
        inValue.id = id;
        return ((IDataLayer)(this)).DeleteDataByIdAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    FindDataByValueResponse IDataLayer.FindDataByValue(FindDataByValueRequest request)
    {
        return base.Channel.FindDataByValue(request);
    }

    public System.Data.DataTable FindDataByValue(string connectionString, string tableName, string columnName, string columnValue)
    {
        FindDataByValueRequest inValue = new FindDataByValueRequest();
        inValue.connectionString = connectionString;
        inValue.tableName = tableName;
        inValue.columnName = columnName;
        inValue.columnValue = columnValue;
        FindDataByValueResponse retVal = ((IDataLayer)(this)).FindDataByValue(inValue);
        return retVal.FindDataByValueResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<FindDataByValueResponse> IDataLayer.FindDataByValueAsync(FindDataByValueRequest request)
    {
        return base.Channel.FindDataByValueAsync(request);
    }

    public System.Threading.Tasks.Task<FindDataByValueResponse> FindDataByValueAsync(string connectionString, string tableName, string columnName, string columnValue)
    {
        FindDataByValueRequest inValue = new FindDataByValueRequest();
        inValue.connectionString = connectionString;
        inValue.tableName = tableName;
        inValue.columnName = columnName;
        inValue.columnValue = columnValue;
        return ((IDataLayer)(this)).FindDataByValueAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    FindDataByIdResponse IDataLayer.FindDataById(FindDataByIdRequest request)
    {
        return base.Channel.FindDataById(request);
    }

    public System.Data.DataTable FindDataById(string connectionString, string tableName, string idColumnName, int idValue)
    {
        FindDataByIdRequest inValue = new FindDataByIdRequest();
        inValue.connectionString = connectionString;
        inValue.tableName = tableName;
        inValue.idColumnName = idColumnName;
        inValue.idValue = idValue;
        FindDataByIdResponse retVal = ((IDataLayer)(this)).FindDataById(inValue);
        return retVal.FindDataByIdResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<FindDataByIdResponse> IDataLayer.FindDataByIdAsync(FindDataByIdRequest request)
    {
        return base.Channel.FindDataByIdAsync(request);
    }

    public System.Threading.Tasks.Task<FindDataByIdResponse> FindDataByIdAsync(string connectionString, string tableName, string idColumnName, int idValue)
    {
        FindDataByIdRequest inValue = new FindDataByIdRequest();
        inValue.connectionString = connectionString;
        inValue.tableName = tableName;
        inValue.idColumnName = idColumnName;
        inValue.idValue = idValue;
        return ((IDataLayer)(this)).FindDataByIdAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    EditDataByIdResponse IDataLayer.EditDataById(EditDataByIdRequest request)
    {
        return base.Channel.EditDataById(request);
    }

    public void EditDataById(string connectionString, string tableName, string idColumnName, int idValue, string parameters, string data)
    {
        EditDataByIdRequest inValue = new EditDataByIdRequest();
        inValue.connectionString = connectionString;
        inValue.tableName = tableName;
        inValue.idColumnName = idColumnName;
        inValue.idValue = idValue;
        inValue.parameters = parameters;
        inValue.data = data;
        EditDataByIdResponse retVal = ((IDataLayer)(this)).EditDataById(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<EditDataByIdResponse> IDataLayer.EditDataByIdAsync(EditDataByIdRequest request)
    {
        return base.Channel.EditDataByIdAsync(request);
    }

    public System.Threading.Tasks.Task<EditDataByIdResponse> EditDataByIdAsync(string connectionString, string tableName, string idColumnName, int idValue, string parameters, string data)
    {
        EditDataByIdRequest inValue = new EditDataByIdRequest();
        inValue.connectionString = connectionString;
        inValue.tableName = tableName;
        inValue.idColumnName = idColumnName;
        inValue.idValue = idValue;
        inValue.parameters = parameters;
        inValue.data = data;
        return ((IDataLayer)(this)).EditDataByIdAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    FindDataResponse IDataLayer.FindData(FindDataRequest request)
    {
        return base.Channel.FindData(request);
    }

    public System.Data.DataTable FindData(string connectionString, string tableName, string filterExpression)
    {
        FindDataRequest inValue = new FindDataRequest();
        inValue.connectionString = connectionString;
        inValue.tableName = tableName;
        inValue.filterExpression = filterExpression;
        FindDataResponse retVal = ((IDataLayer)(this)).FindData(inValue);
        return retVal.FindDataResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<FindDataResponse> IDataLayer.FindDataAsync(FindDataRequest request)
    {
        return base.Channel.FindDataAsync(request);
    }

    public System.Threading.Tasks.Task<FindDataResponse> FindDataAsync(string connectionString, string tableName, string filterExpression)
    {
        FindDataRequest inValue = new FindDataRequest();
        inValue.connectionString = connectionString;
        inValue.tableName = tableName;
        inValue.filterExpression = filterExpression;
        return ((IDataLayer)(this)).FindDataAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ProductNameWithQuantityBiggerThan50HorizontalResponse IDataLayer.ProductNameWithQuantityBiggerThan50Horizontal(ProductNameWithQuantityBiggerThan50HorizontalRequest request)
    {
        return base.Channel.ProductNameWithQuantityBiggerThan50Horizontal(request);
    }

    public System.Data.DataTable ProductNameWithQuantityBiggerThan50Horizontal()
    {
        ProductNameWithQuantityBiggerThan50HorizontalRequest inValue = new ProductNameWithQuantityBiggerThan50HorizontalRequest();
        ProductNameWithQuantityBiggerThan50HorizontalResponse retVal = ((IDataLayer)(this)).ProductNameWithQuantityBiggerThan50Horizontal(inValue);
        return retVal.ProductNameWithQuantityBiggerThan50HorizontalResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ProductNameWithQuantityBiggerThan50HorizontalResponse> IDataLayer.ProductNameWithQuantityBiggerThan50HorizontalAsync(ProductNameWithQuantityBiggerThan50HorizontalRequest request)
    {
        return base.Channel.ProductNameWithQuantityBiggerThan50HorizontalAsync(request);
    }

    public System.Threading.Tasks.Task<ProductNameWithQuantityBiggerThan50HorizontalResponse> ProductNameWithQuantityBiggerThan50HorizontalAsync()
    {
        ProductNameWithQuantityBiggerThan50HorizontalRequest inValue = new ProductNameWithQuantityBiggerThan50HorizontalRequest();
        return ((IDataLayer)(this)).ProductNameWithQuantityBiggerThan50HorizontalAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalResponse IDataLayer.OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000Vertical(OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalRequest request)
    {
        return base.Channel.OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000Vertical(request);
    }

    public System.Data.DataTable OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000Vertical()
    {
        OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalRequest inValue = new OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalRequest();
        OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalResponse retVal = ((IDataLayer)(this)).OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000Vertical(inValue);
        return retVal.OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalResponse> IDataLayer.OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalAsync(OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalRequest request)
    {
        return base.Channel.OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalAsync(request);
    }

    public System.Threading.Tasks.Task<OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalResponse> OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalAsync()
    {
        OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalRequest inValue = new OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalRequest();
        return ((IDataLayer)(this)).OrderIdWhereEmployeeNameStartWithDandSumBetween500and1000VerticalAsync(inValue);
    }
}
